### PR TITLE
Nb/new style

### PR DESCRIPTION
**Pull request by Notika314**
@trevornelson @chrisseldo

### CODE REVIEW

**Comment by Notika314** [comment]
Hi Trevor for some reason user can not go t show page, although I can see
that on users/:id page all params are read correctly. Is there some logic
missing in our code?

**Comment by trevornelson** [comment]
Hey Natalia, 

It's working for me. You're logged in right? I'll take a look tomorrow morning. It could be that it's throwing an error with new users that dont have any surveys created yet. I've just been testing with the seeded users.

-----Original Message-----

**Comment by Notika314** [comment]
Hi Trevor,
 I see, I was testing with new user, that did not have surveys yet, that's
why. That mean also if someone creates account, he won't proceed to show
page as well.
Do you plan to come earlier tomorrow so we can check everything and talk
about presentation as well?

**Comment by Notika314** [comment]
Never mind, seems from 'users/:id' route that user will be proceeding to
show page

**Comment by chrisseldo** [comment]
I think the error has to do with the fact that the new user has 'nil' amount of surveys to display on the 'user/:id' page. We can fix that part in the morning.

**Comment by Notika314** [comment]
I see, thanks!

**Comment by trevornelson** [comment]
Yeah I'm going in early tomorrow. I'm shooting to be there around 8 if I can.

-----Original Message-----

**Comment by chrisseldo** [comment]
Yes. I'll probably need some help with the 'create survey forms' tomorrow morning as well.

**Comment by chrisseldo** [comment]
Until then, goodnight!

**Pull request merged**
